### ISSUE TITLE
Platform flag not working as expected when exposing a resource in Skupper

### ISSUE THREAD

**Issue by nluaces** [skupperproject/skupper#1147]
## Expected Behavior
I was using podman to run a posgresql database, and did not set up the `SKUPPER_PLATFORM` environment variable.
After creating a skupper site with `--platform podman`, I used the same flag to expose the database into the VAN:
```
skupper expose host  database --address localhost --port 5432 --platform podman
```

## Current Behavior
It did not expose the database because it didn't recognize the target type host, but the command accepts the flag --platform.
After that, I exported SKUPPER_PLATFORM with the podman value, exposed the database with 

`skupper expose host  database --address localhost --port 5432`

and it worked fine.

## Failure Information 
```
skupper expose host  database --address localhost --port 5432 --platform podman                 
Error: target type must be one of: [deployment, statefulset, pods, service, deploymentconfig]
[...]
```

### Context
* skupper version: 1.4.0-rc4

**Comment by nluaces** [comment]
In the init command is happening something similar, and the issue is that the selection of Podman Skupper client or Kubernetes Skupper client happens before reading the value from the flag in the command.

The first time it is executed here: https://github.com/skupperproject/skupper/blob/d9aaf1c3849627f4a37064382d2f917520a431ae/cmd/skupper/skupper.go#L981 which does not contemplates the value of the flag because it is not being executed yet, so the skupper client is already set to the platform defined by the env variable. That also impacts the flags that are shown with the --help flag.

**Comment by fgiorgetti** [comment]
I believe the issue is related with the positional arguments being evaluated.
If you use `skupper --platform podman` (passing the --platform right after the skupper binary) it seems to work.

There might be something wrong with the parsing of `--platform` when it is mixed with the respective
sub-command arguments.

**Comment by gabordozsa** [comment]
I think I have found the root cause for this. Basically, the parsing of `--platform` happens very early in the` init()` in order to decide which type of client to instantiate. However, no other flags are defined yet at that point. This causes the parsing to fail if any other flag is encountered in the command line before the '--platform' one. I'm going to open a PR to fix this shortly.
