### ISSUE TITLE
Skupper controller error using Openshift authentication 

### ISSUE THREAD

**Issue by bartoval** [skupperproject/skupper#1235]
Skupper 1.4.2
I executed the following command:
`skupper init --enable-console --enable-flow-collector --console-auth openshift`

Following this command, Openshift presented me with an error message in the controller, specifically the "createContainerConfigError." However, there were no error logs found in the controller, collector, or auth_proxy components.

Here is the error message screenshot for reference:![oc](https://github.com/skupperproject/skupper/assets/79913332/e3e68998-c12f-41f2-b067-9275dca38f6f)

**Comment by fgiorgetti** [comment]
It seems like the openshif oauth-proxy image is set to run as root, but the
deployment setting `runAsNonRoot` as true. We need to fix it.

**Comment by fgiorgetti** [comment]
Actually, after investigating an unrelated issue, I have noticed that the images are not the problem.
The problem is that some OpenShift clusters have a restricted Security Context Constraint (scc) that
only allows running containers with certain user and groups.

You can validate that by running:

`oc get ns default -o json | jq -r '.metadata.annotations."openshift.io/sa.scc.uid-range"'`

So if that is the case, then skupper must be initialized to run as a user under the provided uid-range.

@grs @ajssmith @nluaces I believe that skupper (or at least the site-controller) could try to detect that
when running on OCP and adjust the user/group to be used by Skupper Containers based on the defined ranges.
Thoughts?
