### ISSUE TITLE
Confusing "sync failed" message in config-sync log

### ISSUE THREAD

**Issue by gabordozsa** [skupperproject/skupper#1545]
There are messages like:
```
2024/07/16 10:43:41 sync failed: Bridge config is not synchronised yet
```
in the config-sync log whenever bridge config changed (i.e. listeners/connectors added or deleted). The reason for the log message is that the `syncConfig()` function always returns value `false` whenever the bridge config changed: https://github.com/skupperproject/skupper/blob/c26bce4079fffbd19a98656713428fc57e037452/cmd/config-sync/config_sync.go#L203.

Is this `false` return value correct here? As all the calls for the sync succeeded at this point it is confusing to see a "sync failed" error message. On the other hand,  if this is a bug and the return value should be `true` here then this `synced` return flag seems to be superfluous as it simply denotes if an error occurred or not.

**Comment by grs** [comment]
I agree the log message is confusing, indeed I would say it is wrong as it is emitted even when nothing has failed. The boolean flag returned by syncConfig() is true if the config as retrieved from the router is as desired, false otherwise (even if actions have been taken to alter the router config in line with what is desired).

However ConfigSync.syncConfig(), which calls the syncConfig() function, simply returns an error losing the distinction. This I think is the root of the confusion.

I think the simplest solution would be to replace lines 220-222
```
if !synced {
    return fmt.Errorf("Bridge config is not synchronised yet")
}
```
with
```
if synced {
    log.Println("Bridge config is synchronised")
}
```
