### ISSUE TITLE
improve doc for --cluster-local and --edge options

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#217]

**Comment by pwright** [comment]
@grs  I'm trying to provide describe the behaviour (what you can and can't do), and include some typical use-cases, but am I going too far?:

| Option  | Description  |
|---|---|
| none  | Allows you to create a connection to and from this site. This is known as an interior site and is the default site type. Typically you create interior sites on public clouds to allow for service discovery. | 
| edge | Allows you to create a connection from this site. You cannot create a connection to this site. Only one active connection is allowed with this site, however you can switch connections. For example, you can create a connection from this site to two interior sites. The current active connection is the last connection created. Typically you do not create a connection from an edge site to a cluster-local site because service discovery is typically not possible from either of those site types. |
| cluster-local | Allows you to create a connection to and from any site in the current cluster. You can also create a connection to any interior site, including sites outside the current cluster. |

**Comment by grs** [comment]
I see these as two orthogonal options. One controls whether anything is exposed outside the cluster. The other controls whether the site allows other sites to connect to it. To me the table above confuses things. (I'm also somewhat wary of using the term 'interior site' in this way).

The cluster-local option prevents any of the skupper site services being exposed for access from clients outside the kubernetes cluster the site is in. (I.e. there will be no Routes created on openshift, nor LoadBalancer type services on other platforms. A site with cluster-local can still create connection tokens and have other sites use those to connect to it, but the tokens are only valid from other namespaces within the same cluster. The console is also not exposed outside the cluster.

An edge site is one that will not have any other sites connecting to it. Such sites do not allow connection tokens to be created as there is no use for them. The console however will by default be exposed as a Route or a LoadBalancer type service.

**Comment by pwright** [comment]
Take 2 (avoiding 'interior'.. Also, not mentioning console, but could add 3rd column to handle that ):


| Option  | Description  |
|---|---|
| none  | A default site allows incoming connections from inside and outside the cluster. A default site can generate tokens that are valid from other sites. To connect to a default site from another cluster, the default site must be accessible, for example on a public cluster.| 
| edge | An edge site cannot accept incoming connections. Typically, it requires access to the public Internet to connect to other sites. An edge site cannot generate tokens. |
| cluster-local | Allows you to create a connection to and from any site in the current cluster. You can also create a connection to any site on other accessible clusters.  A cluster-local site can generate tokens that are valid from other sites in the same cluster. |

**Comment by pwright** [comment]
@grs wdyt of above? An alternative might be to demote 'edge' to 'Scaling your Skupper topology' documentation and avoid mentioning it outside that context?

**Comment by grs** [comment]
> An alternative might be to demote 'edge' to 'Scaling your Skupper topology' documentation and avoid mentioning it outside that context

I like that idea.

**Comment by nluaces** [comment]
Closing this ticket due inactivity. Feel free to reopen if the issue still exists.
