### ISSUE TITLE
Support optional tear down in integration tests.

### ISSUE THREAD

**Issue by nicob87** [skupperproject/skupper#47]
For this the testing miniframework that we have must create namespaces with some hash or suffix, making them unique, so if the previous run has not deleted its namespace, the new run does not clash.
Possibly at the end we can have a "clenup" function that remove all namespaces matching our test_namespace preffix.
In the case of CI this is not so important, since the vm is destroyed anyway, but if we run in a persistent cluster, having some clean-up is desired.
Specifically this is very useful for reducing the testing time, for simple, low resource consumption tests, it is easy to just, "do not tear down" and continue with the next test.

**Comment by fgiorgetti** [comment]
Makes sense, but I would like also to add that we must have support for both approaches, allowing tear down after each test, and also, once single after all tests. It will depend on the intents of each test.
The reason why some people recommend using a full setup and tear down is because it allows you to run multiple tests in parallel and using any order. That's why I believe it might be better to allow both.

**Comment by nicob87** [comment]
Correct! the idea is to support both.
