### ISSUE TITLE
Gateway unbind on downloaded (and active) gateway is not working

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#535]
I am seeing an error running `gateway unbind` on a gateway that has been downloaded and installed.

```
skupper -n sk1 gateway unbind tcp-echo-host  --name prepared-gateway
Error: Failed to read instance url file: open /home/user/.local/share/skupper/prepared-gateway/config/url.txt: no such file or directory
```

**Comment by ajssmith** [comment]
To clarify, was the gateway initialized as --downloadonly?

Presently, gateway commands do not affect bundles that have been downloaded. It would require that the gateway be downloaded again after any configuration change. Recognize that this is not the best for usability but the expectation is that download is for systems that otherwise do no have cluster access.  That said, there are likely some additional checks
that can be made in the unbind command to detect the condition.

Long term this will be better addressed with dedicated download commands to work from a configuration .yaml to generate a bundle for download so it is clear to the user the relationship.

**Comment by fgiorgetti** [comment]
> To clarify, was the gateway initialized as --downloadonly?

Yes, it was.

> Presently, gateway commands do not affect bundles that have been downloaded. It would require that the gateway be downloaded again after any configuration change. Recognize that this is not the best for usability but the expectation is that download is for systems that otherwise do no have cluster access. That said, there are likely some additional checks that can be made in the unbind command to detect the condition.

I agree. In such cases, it would be nice just to warn user instead of reporting an error.
