### ISSUE TITLE
Consider `skupper token validate` subcommand

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#710]
This would be run at the issuing site and would simplify the debugging needed to asses the validity of a token (checking ca and verifiying signature, checking hostname, checking time).

**Comment by lynnemorrison** [comment]
@grs I'd like to attempt this enhancement

**Comment by lynnemorrison** [comment]
@grs I want to verify what you are looking for here:

user would issue a command:
skupper token status ~/token.txt

code would read this file and also read secret from Kube/podman with name field from ~/token.txt and verify

I can add code to verify that the secret is created by the local router and if so continue with the checks otherwise just return,
you mentioned above that command is run on issuing router?

print token expiration and if it has expired  (compare time against time.now(), for expiration)
print how many uses are left
how should I be checking the CA?  just verifying the CA in the token.txt and the CA in the kube/podman secret skupper-local-client CA match?

when you mention hostname above I don't see a host name in any of the secrets,  I just see name.   Is that the field you are referring to?

Is there other fields I should be checking?

**Comment by grs** [comment]
The idea was to automate some of the checking required when debugging connectivity issues. It is really relevant only for certificate type tokens, not claims. The CA in the cert token could be compared to the CA in the skupper-site-server secret, reporting if they match or not. A step further is to actually verify the certificates were indeed both signed by that CA. And then a further step is to check that the tls.crt in the skupper-site-server secret has a hostname or IP in its SANs list that matches the annotation on the token.
