### ISSUE TITLE
Removal of policies followed by re-allowing: should services be removed?

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#727]
# How to reproduce?

- Create a policy that allows skupper services to be created
- Create a skupper service
- Remove the initial policy
- Immediatelly after that, re-establish a policy that allows that skupper service to exist

# Expected behavior

Unknown: should the service have been removed (as at a very small point in time there was no policy allowing it), or should it be allowed to stay (keep)?

# Actual behavior

Testing the scenario reveals that currently the second option (keep) is true; the service is allowed to stay.  Is that the correct behavior?

# Additional concerns

Even if the second option (keep) is the correct behavior, there is a concern that it may be non-deterministic.  Testing to confirm that is currently underway.  The rationale is that most of the time the system simply does not see the intermediate state, but that on a specific timing in the cycle it might do.

Note that the scenario is not artificial.  It should be expected that handling of policies may be done by automation (simple scripts or GitOps/DevOps pipelines).  In that scenario, the removal of a policy followed by something that replaces it (instead of changing an existing policy) should not be a rare case.

Also note that this differs from most declarative changes in that there is a collateral effect when a policy is changed to disallow a service and then reinstated: the service is removed when it is disallowed, and it is not recreated when it is allowed back.

**Comment by hash-d** [comment]
On the additional concern: I have tested the scenario some 1,500 times, and the first option (remove) never occurred.  However, the question now becomes: what means 'immediate'?  I'm repeating the test with 500 repetitions, and a slowly and always increasing sleep between them, to see at what point the behavior changes.  That, of course, will be system-dependent.

An additional note that the test has failed in other points, and other issues will be opened for it.

**Comment by hash-d** [comment]
The retest increased the time between removing the policy and re-adding it by 10ms every cycle, from 0 to 5000ms.  The results on when the behavior changed follow:

- Test #1 - 520ms
- Test #2 - 410ms
- Test #3 - 460ms
- Test #4 - 540ms
- Test #5 - 480ms

So, around 0.5s after the policy is removed, the behavior changes.

**Comment by fgiorgetti** [comment]
Policies are managed (CRUD) directly by the Kube API, and every time a policy is added, removed or updated, an event is consumed by the controller instances running in the cluster.

When the controller consumes the respective event, it reads the "current" state for the given namespace, in order to determine what is allowed and what is not.

Those 2 processes (CRUD x Policy processing) are asynchronous, and so as the controller is processing policy changes, new policy (CRUD) events may have already been performed by Kube API.

Given that, I believe that we should educate users on the recommended approach to manage policies.

As already documented, policies are evaluated using an **or** operator, thus if at least one policy authorize a given action, that action will be considered as allowed, in spite of the presence of other policies that do not allow it.

With that said, I would recommend, to avoid disruption in the services or other allowed actions, that users must first add or update their policies to ensure what is expected to be allowed is granted by other policies.

Once you have at least one other policy that preserves the authorization, you can remove or clean up other policies, to prevent service disruption on authorized sites.

@pwright what do you think?

**Comment by pwright** [comment]
@fgiorgetti How about something like:

# Maintaining policies

Over time, the policy CRs might become unclear, this section helps you understand and maintain your policy CRs.

1. Retrieve all applied policy CRs:

`$ kubectl get SkupperClusterPolicy -o yaml`

2. Review the policies for each category:

For example, search the output of step 1 for `allowedOutgoingLinksHostnames`.

If you find an entry like `allowedOutgoingLinksHostnames: ['.*']` that applies to all namespaces, that means that there is no restriction on outgoing links, even if there is a different restrictive entry, for example `allowedOutgoingLinksHostnames: ['.*\\.example\\.com']`.

3. After reviewing, remove any entries from the original CRs that cause confusion and reapply those CRs

**Comment by fgiorgetti** [comment]
In V2, permissions to manipulate Skupper resources will be granted via RBAC.
Eventual enhancements needed to policy will be done in V2.
