### ISSUE TITLE
Highlight "pending" status because the console url is displayed and might not be available

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#992]
```
$ skupper status
Skupper is enabled for namespace "default" in interior mode. Status pending... It has no exposed services.
The site console url is:  https://10.103.37.45:8080
The credentials for internal console-auth mode are held in secret: 'skupper-console-users'
```
I missed the pending status and clicked the url, but it wasn't there yet..
Maybe if 'pending' was highlighted with quotes it would help?

**Comment by hash-d** [comment]
I think highlighting 'pending' might be good, but I'd definitely not take the console url out because of skupper status.  I don't know all reasons it would be non-ready, but it's conceivable that the console might be up even though skupper as a whole is not, and it could be useful into debugging why it is not.

**Comment by pwright** [comment]
@hash-d +1 changed issue title

**Comment by pwright** [comment]
I believe this is being addressed in v2
